<?php
use \Drupal\Core\Form\FormStateInterface;
function hello_help($route_name, \Drupal\Core\Routing\RouteMatchInterface $route_match) {
  switch ($route_name) {

    // Main module help for the block module.
    case 'help.page.hello':
      return '<p>' . t('HELLO NAIM') . '</p>';


  }
}

function hello_cron() {

  $purge_days_number = \Drupal::config('hello.settings')
    ->get('purge_days_number');
  if ($purge_days_number != '0') {
    $nombre_suppresion = \Drupal::database()
      ->delete('hello_user_statistics')
      ->condition('time', REQUEST_TIME - $purge_days_number * (24 * 3600), '<')
      ->execute();
    \Drupal::messenger()
      ->addMessage(t('@nombre_suppressions records have been deleted.', ['@nombre_suppressions' => $nombre_suppresion]));
  }

}



 function hello_user_login(Drupal\user\UserInterface $account) {
   //ksm(\Drupal::database());
   $roles = \Drupal::config('hello.settings')->get('role_user_connexion');
   $user_roles= $account->getRoles();
   //array_intersect compare deux elements dans un tableau et en créer un autre
   $diff = array_intersect($roles, $user_roles);
   if(count($diff)>'0') {
     \Drupal::database()->insert('hello_user_statistics')
       ->fields([
       'uid' => $account->id(),
       'action' => '1',
       'time' => REQUEST_TIME,
     ])
     ->execute();
   }
}
  function hello_user_logout(\Drupal\Core\Session\AccountInterface $account) {
    //ksm(\Drupal::database());
    \Drupal::database()->insert('hello_user_statistics')->fields([
      'uid'=> $account->id(),
      'action'=>'0',
      'time'=>REQUEST_TIME,
    ])
      ->execute();
    \Drupal::messenger()->addMessage(t('Sign-Up.'));
  }

function hello_theme(){
  return array(
    'hello_user_connexion'=>array(
      'template'=> 'hello-user-connexion',
      'variables'=>array(
        'user' => Null,
        'count' =>Null),
    ),
  );
}

function hello_form_user_admin_settings_alter(array &$form, FormStateInterface $form_state){



  $roles_config= \Drupal::config('hello.settings')->get('role_user_connexion');

  $roles= \Drupal::entityTypeManager()->getStorage('user_role')->loadMultiple();
  ksm($form);
  unset($roles['anonymous']);
  foreach ($roles as $key=>$role){
    $options[$key] = $role->label();
  }

  $form['test']=[
    '#type'=>'details',
    '#title'=>t('Roles for wich to collect activity statistics.'),
    '#open'=>TRUE,
    '#weight'=> '-100',
  ];
  $form['test']['roles']=[
    '#type'=>'checkboxes',
    '#options'=>$options,
    '#default_value'=> $roles_config,
    ];
  $form['#submit'][]='hello_form_admin_settings_submit';

}
  function hello_form_admin_settings_submit(array &$form, FormStateInterface $form_state){
  $config = \Drupal::configFactory()->getEditable('hello.settings');
  $config->set('role_user_connexion',$form_state->getValue('roles'))->save();

  }