<?php

function hello_help($route_name, \Drupal\Core\Routing\RouteMatchInterface $route_match) {
  switch ($route_name) {

    // Main module help for the block module.
    case 'help.page.hello':
      return '<p>' . t('HELLO NAIM') . '</p>';


  }
}

function hello_cron() {

\Drupal::messenger()->addMessage(t('Hello cron'));
}


 function hello_user_login(Drupal\user\UserInterface $account) {
   ksm(\Drupal::database());
    \Drupal::database()->insert('hello_user_statistics')->fields([
       'uid'=> $account->id(),
       'action'=>'1',
       'time'=>REQUEST_TIME,
      ])
      ->execute();

  \Drupal::messenger()->addMessage(t('Welcome dear %name!',
  ['%name'=>$account->getAccountName()]
  ));
}
  function hello_user_logout(\Drupal\Core\Session\AccountInterface $account) {
    ksm(\Drupal::database());
    \Drupal::database()->insert('hello_user_statistics')->fields([
      'uid'=> $account->id(),
      'action'=>'0',
      'time'=>REQUEST_TIME,
    ])
      ->execute();
    \Drupal::messenger()->addMessage(t('Sign-Up.'));
  }