<?php
function hello_help($route_name, \Drupal\Core\Routing\RouteMatchInterface $route_match) {
  switch ($route_name) {

    // Main module help for the block module.
    case 'help.page.hello':
      return '<p>' . t('HELLO NAIM') . '</p>';


  }
}
function hello_cron() {

\Drupal::messenger()->addMessage(t('Hello cron'));
}


 function hello_user_login(Drupal\user\UserInterface $account) {
 \Drupal::messenger()->addMessage(t('Welcome dear %name!',
  ['%name'=>$account->getAccountName()]
));
}
